name: Rust Simple Check CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  quick_check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust Stable
      uses: dtolnay/rust-toolchain@stable

    - name: Cargo Cache Setup
      uses: swatinem/rust-cache@v2

    # --- THE MAGIC FLAG: Sirf code check karo, build mat karo ---
    - name: Run Syntax and Validity Check
      run: cargo check
